//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poprig
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Agent()
        {
            this.Sales = new HashSet<Sales>();
        }
    
        public int ID { get; set; }
        public string Title { get; set; }
        public Nullable<int> TypeID { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string LogoPath { get; set; }
        public string UrAdres { get; set; }
        public Nullable<int> Prioritet { get; set; }
        public string ContactPerson { get; set; }
        public string INN { get; set; }
        public string KPP { get; set; }

        public int SalesOnYear { get; set; }
        public float Skidka { get; set; }

       public string AllPathLogo { get; set; }

        public virtual TypeAgent TypeAgent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sales> Sales { get; set; }
    }
}
