//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poprig
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyDB_41_Derbin_2Entities : DbContext
    {
        public static MyDB_41_Derbin_2Entities Context;

        public static MyDB_41_Derbin_2Entities GetContext()
        {
            if (Context==null) Context= new MyDB_41_Derbin_2Entities();
            return Context;
        }
        public MyDB_41_Derbin_2Entities()
            : base("name=MyDB_41_Derbin_2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agent> Agent { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Sales> Sales { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypeAgent> TypeAgent { get; set; }
        public virtual DbSet<TypeProduct> TypeProduct { get; set; }
    }
}
